### ISSUE TITLE
Add link to official nuget package (if there is one)

### ISSUE THREAD

**Issue by petsuter** [IronLanguages/ironpython.net#3]
Is there an official Nuget package of Iron Python? I don't see a link anywhere.
Is https://www.nuget.org/packages/IronPython controlled and maintained by the project?
Please consider adding a link to the official Nuget package of Iron Python to confirm this (if true). Thanks.

**Comment by jdhardy** [comment]
Yes, that's official. I'll update the downloads page to make that more obvious.
