### ISSUE TITLE
Link to eBook IronPython in Action is broken

### ISSUE THREAD

**Issue by stackh34p** [IronLanguages/ironpython.net#32]
Hello,

On the https://ironpython.net/documentation/ page, there is a link to the eBook "Iron Python in Action". The domain it points to seems to no longer be relevant, and a different page opens. 
Maybe you'd want to fix the link.

Cheeers

**Comment by slozier** [comment]
Thanks for the report! It's unfortunate that the "IronPython in Action" site is dead (as well as the author's site...). 😢

**Comment by slozier** [comment]
Updated with link to wayback machine.
