### ISSUE TITLE
Update Documentation page

### ISSUE THREAD

**Issue by petsuter** [IronLanguages/ironpython.net#4]
The http://ironpython.net/documentation/ page seems to be quite outdated.

> Since IronPython is a implementation of Python 2.6, any Python documentation is useful when using IronPython.
> Python 2.6 documentation

I assume this should be changed from 2.6 to 2.7?
There are still a lot of links to codeplex. Are these still the most up to date resources?
Are the docs from https://github.com/IronLanguages/ironpython-docs linked to anywhere?

Is there any up-to-date documentation on the assemblies included with Iron Python? (E.g. what is IronPython.Wpf.dll? When do I need it?)

**Comment by jdhardy** [comment]
I know :( It's horrifically out of date. I should have some time in the next couple of days to get rid of the worst errors, but there's a lot of legacy stuff (like WPF support) that I simply don't know enough about to update.

**Comment by petsuter** [comment]
Thanks for the updates. 

Regarding IronPython.WPF: It seems to have been added in http://ironpython.codeplex.com/SourceControl/changeset/75203

> Changeset Id: 1956311
> Date: 8/4/2010 12:48:54 PM
> 
> Moves IronPython’s LoadComponent support to a new (optional) wpf module. This enables it to depend upon WPF which fixes a bug where data binding isn’t working when we use the default XAML schema context. The DLL is added to the DLLs directory and everything including the MSI is updated to include it. Test_dllsite needed to be updated to deal w/ the presence of this directory. Also re-orders the parameters to that the target object comes first in LoadComponent.
> 
> To keep the balance of DLLs the same this gets rid of Microsoft.Scripting.Debugging and folds that into Microsoft.Dynamic.dll (this was planned anyway after Tomas added the metadata DLL).
> 
> The assembly load order has changed and this broke test_interactive – including the extensions causes us to do a LoadFile when we want a normal load.
> 
> (Shelveset: wpfdllsfinal;REDMOND\dinov | SNAP CheckinId: 11236)
